; AUTOGENERATED CODE
PUSH 52
POP  [0]     ; a
PUSH [0]     ; a
OUT
; call
; giving args
PUSH 6
POP  [2]     ; 0 + 2
; ended giving args
; pushing old base pointer (RBX)
PUSH RBX
; shifting base pointer (RBX)
PUSH 2
POP  RBX
; ended shifting base pointer (RBX)
CALL foo:
POP  RBX
PUSH RAX
; call ended
POP  [1]     ; ans
JMP END_OF_FUNC_foo: ;skipping func body
foo:
PUSH 5
POP  [RBX 0] ; a (local)
PUSH [RBX 0] ; a (local)
OUT
PUSH 0
POP  RAX
RET
END_OF_FUNC_foo:
PUSH [0]     ; a
OUT
HLT
